### ISSUE TITLE
minetest.register_on_mods_loaded instead of minetest.after

### ISSUE THREAD

**Issue by ghost** [taikedz/everamzah-superpick#3]
Using `minetest.after` while loading the mod seems to mess up the node definitions (possible race condition with other mods that iterate over the nodes?).

By using `minetest.register_on_mods_loaded` this can be solved entirely.

Just replace [this code](https://github.com/everamzah/superpick/blob/3f5f33b81f379591314b5ccc4ddb835be07257d6/init.lua#L76-L100) with this code:

```Lua
minetest.register_on_mods_loaded(function()
	for node in pairs(minetest.registered_nodes) do
		local def = minetest.registered_nodes[node]
		for i in pairs(def) do
			if i == "on_punch" then
				local rem = def.on_punch
				local function new_on_punch(pos, node, puncher, pointed_thing)
					kill_node(pos, node, puncher)
					return rem(pos, node, puncher, pointed_thing)
				end
				minetest.override_item(node, {
					on_punch = new_on_punch
				})
			end
		end
	end
end)
```

… [as discussed/discovered here](https://forum.minetest.net/viewtopic.php?p=349291#p349291).

**Comment by taikedz** [comment]
Hi Linuxdirk

Want to fork/commit/PR ? Take credit for the effort and all....

**Comment by LoneWolfHT** [comment]
> Hi Linuxdirk
> 
> Want to fork/commit/PR ? Take credit for the effort and all....

If they don't want to, I can

**Comment by ghost** [comment]
@LoneWolfHT Please do so :smile: My account here is just used for comments and discussion. I’m not giving Microsoft any code :penguin:

**Comment by taikedz** [comment]
Thanks y'all :-)

**Comment by ghost** [comment]
Lovely :+1:  That’s teamwork, I guess :smile:
